export const DIALOG_EVENTS = {
    OPEN_CONFIRM_ACTION_BASED_EVENT_DIALOG : "OPEN_CONFIRM_ACTION_BASED_EVENT_DIALOG",
    OPEN_LOCATION_IS_DISABLED_BASED_EVENT_DIALOG : "OPEN_LOCATION_IS_DISABLED_BASED_EVENT_DIALOG",
    OPEN_RECIPT_METHOD_BASED_EVENT_DIALOG : "OPEN_RECIPT_METHOD_BASED_EVENT_DIALOG",
    OPEN_NEW_CREDIT_CARD_BASED_EVENT_DIALOG : "OPEN_NEW_CREDIT_CARD_BASED_EVENT_DIALOG",
    OPEN_NEW_ADDRESS_BASED_EVENT_DIALOG : "OPEN_NEW_ADDRESS_BASED_EVENT_DIALOG",
    OPEN_STORE_ERROR_MSG_BASED_EVENT_DIALOG : "OPEN_STORE_ERROR_MSG_BASED_EVENT_DIALOG",
    OPEN_STORE_IS_CLOSE_BASED_EVENT_DIALOG : "OPEN_STORE_IS_CLOSE_BASED_EVENT_DIALOG",
    OPEN_DELIVER_METHOD_AGGREE_BASED_EVENT_DIALOG : "OPEN_DELIVER_METHOD_AGGREE_BASED_EVENT_DIALOG",
    OPEN_INVALID_ADDRESS_BASED_EVENT_DIALOG : "OPEN_INVALID_ADDRESS_BASED_EVENT_DIALOG",
    PLACE_SWITCH_TO_CURRENT_PLACE : "PLACE_SWITCH_TO_CURRENT_PLACE",
    OPEN_PAYMENT_ERROR_MESSAGE_DIALOG : "OPEN_PAYMENT_ERROR_MESSAGE_DIALOG",
  };